### ISSUE TITLE
Blatt 2 Wiki Page

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#11]
Hübsche Wiki-Seite mit Bildeinbindungen gestalten.

**Comment by fft5woosh** [comment]
ja.
Bis Donnerstag sollten wir´s haben, sobald alle Aufgaben als png richtig im UML/Blatt2 verfügbar sind

**Comment by fft5woosh** [comment]
Habe mal eine Wiki erstellt.

**Comment by fft5woosh** [comment]
Ok da müssen wir aber noch diskutieren :-)
Das ist natürlich nur meine Meinung und in **keinster Weise** Kritik :
Es geht nur darum das ich es nachvollziehen kann :

![zzzzzz](https://user-images.githubusercontent.com/43741930/47809851-2699e500-dd42-11e8-9d7e-def096ceb729.PNG)


aufg1 ) 

die Verbindungen vom Akteur zu den Aktivitäten müssen einfache Linien sein und keine Pfeile
(siehe oben)

aufg4 ) 
warum muss _Objekt scharf stellen_ und _Belichtung messen_ synchron verlaufen ?
die Schleife in der abgesichert wird , dass der Blitz auch gezündet wurde wenn die Blende
geöffnet ist fehlt.

aufg6) 
precondition und postcondition  müssen im Diagramm zwischen <<>> vermerkt sein und sind
in der Angabe enthalten.
Als Auslöser hätte ich deshalb ein Signal verwendet und die Ausgabeparameter fehlen noch.
In meinem Diagramm fehlen Start/Endknoten.

aufg8) 
Aus einer Abstrakten Klasse kann kein Objekt erzeugt werden, und Dokumentinhalt und Grafik
sind laut Angabe abstrakt.
Hier verstehe ich auch nicht sofort im Diagramm warum einmal ein Text von Dokumentinhalt erbt 
 und einmal ein Text von Text erbt.
Die Ist-Teil von Beziehung bedeutet auch : Das Dokument als Ganzes besteht aus vielen 
Dokumentinhalten (Texte, Grafiken oder Dokumenten selber)

aufg9) 
Als Instanzen gibt es 2 Texte, 2 Dokumente und eine zusammengesetzte Grafik welche aus 2 
einfachen Grafiken besteht.
die drucken() Methode wird auf diese Instanzen der Reihe nach aufgerufen und das kann man dort
nicht erkennen.

**Comment by Bergmaier** [comment]
Hallo @fft5woosh 
Danke für die Erklärungen. Genau die Kritik finde ich gut - und du hast ja auch recht! Bitte fasse meinen Edit an der Wiki-Seite nicht als Revert deiner Änderungen an den Diagrammen auf - ich habe nur die ganzen Dateien im Repository ein wenig aufgeräumt und auf 2 Branches verteilt.
Sobald wir #13 akzeptieren (und das sollten wir imo tun), werden die neuen Diagramme auf der Wiki-Seite auftauchen.
Lass uns die einzelnen Aufgaben in den jeweiligen Issues diskutieren.

**Comment by fft5woosh** [comment]
Ok geht in Ordnung.
Die Aufteilung mit den Branches  und auch den Wikipages finde ich auch sehr gut.
