### ISSUE TITLE
Filetypen Diagramm

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#12]
Hallo,
es ist imo keine gute Idee sowohl XML als auch PNG hochzuladen - dann muss man sich immer um 2 Dateien kümmern und sie in Sync halten. (Siehe https://en.wikipedia.org/wiki/Single_source_of_truth, https://en.wikipedia.org/wiki/Single-source_publishing)
Die ersten Sachen hatten wir als XML gemacht damit man sie bei draw.io wieder importieren und weiterbearbeiten. @Ruleya und ich haben allerdings am Freitag herausgefunden, dass man bei draw.io auch [beim PNG-Export die Diagramm-Daten behalten kann](https://support.draw.io/display/DO/Exporting+Files):

> Including a copy of the diagram in the image means you can load the diagram back into draw.io using the exported PNG and have a fully editable diagram, rather than a static PNG (i.e. the diagram data is embedded in the PNG). We enable this by default since it can be a useful way to restore a diagram if you lose the XML save. It does increase the size of the PNG, so if you really don't need the data embedded, you can untick this option

Das hat dann den Vorteil gegenüber dem XML, dass wir die Bilder direkt ins Wiki einbinden können.

Außerdem möchte ich mal den [Github mode](https://www.draw.io/?mode=github) ausprobieren, das wäre wahrscheinlich das beste, hat aber am Freitag nicht geklappt.

**Comment by fft5woosh** [comment]
no problem :-) Kann jederzeit mit **git rm** im Repository gelöscht werden^^
Ich dachte mir ich lade die xml zusätzlich hoch damit man nicht nochmal komplett bei 0anfangen muss.
Sehr gut zu wissen, das draw.io aus einer png ein editierbares Dokument erstellt.

**Comment by Bergmaier** [comment]
Ich wusste es bis Freitag auch nicht, das ist sehr gut versteckt :-)

**Comment by fft5woosh** [comment]
sind entfernt worden
