### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by Angiabc** [sweIhm-ws2018-19/skillproject-fr-33#14]
Bitte auf wiki Seite stellen
[Communication sheet.docx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2542595/Communication.sheet.docx)

**Comment by fft5woosh** [comment]
Versuchs mal mit https://github.com/sweIhm-ws2018-19/skillproject-fr-33/wiki/Home/_edit

**Comment by Bergmaier** [comment]
Danke für die Bearbeitung!
