### ISSUE TITLE
Datenbanken

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#15]
Gibt es Datenbanken á la https://quiz.sueddeutsche.de/quiz/2081646851-reise-quiz-berlin/3/answer/2  zu
- Berlin
- Dresden
- Ostsee ?
pro Region bräuchten wir um die 50 Quizfragen.
Dabei sollten es nicht nur Standardfragen wie "Wie viele Einwohner.." etc. sein, sondern eben in die Richtung des Beispiels gehen. Gerne auch lustige Fragen. Wäre super, wenn Ihr uns zeitnah (bis Dienstag, 13.11.) sagen könnt, ob es da schon was gibt. Haben ein bisschen Dampf von unseren Profs bekommen .. :O

**Comment by Bergmaier** [comment]
Ich kenne da nichts. Ich finde zwar ein paar Seiten, wo man Quizzes spielen kann, aber man kann deren Fragen nicht automatisch einbinden. Das müsst ihr euch selbst überlegen - zur Not mit Copy-und-Paste in eine Textdatei die wir im Programm einfach einlesen können.

**Comment by Bergmaier** [comment]
Vielleicht so etwas wie https://opentdb.com/browse.php?query=Geography&type=Category oder https://freequizdatabase.weebly.com/categories.html, aber in diesen Datensätzen gibt es halt keine Informationen auf welche Region sich das bezieht. Das müsste man alles manuell taggen.

**Comment by Bergmaier** [comment]
Am ehesten hätten wir noch Chancen mit [DBpedia](https://de.wikipedia.org/wiki/DBpedia), da es zu vielen lokalen Orten Wikipedia-Einträge gibt. Zum Beispiel http://dbpedia.org/page/Oberammergau - da finden sich unter den vielen Infos etwa die für uns interessanten Attribute "Koordinaten", "Bürgermeister", "Einwohnerzahl", "Geburtsort von" - und diese Attribute gibt es auf sehr vielen Objekten, zu denen allen wir dann automatisch Fragen erstellen können. Ihr könnt mal herumsuchen wozu man sonst noch so Fragen stellen könnte, Berge, Sehenswürdigkeiten, ...? Sucht in der englischsprachigen Wikipedia nach dem Seitentitel und gebt ihn dann bei dbpedia ein, um zu sehen ob es dazu strukturierte Infos gibt.

**Comment by Claraabc** [comment]
Ok danke, dann schauen wir mal selber. Wie braucht ihr denn dann die Daten von uns? Excel oder Word und müssen die nach irgend nem bestimmten Schema angeordnet sein? 🙃

**Comment by Bergmaier** [comment]
Hallo, Tabellenform sollte es sein - also eher Excel, Word keinesfalls. Excel kann dann auch als [CSV](https://de.wikipedia.org/wiki/CSV_(Dateiformat)) oder so exportieren.
Spalten sollten sein etwa "Region (Wikipedia-Link)" oder "Geokoordinaten", dann "Frage", "richtige Antwort", "Alternative 1", "Alternative 2"...

**Comment by rena611** [comment]
Wir sind dran die Fragen in ein Excel Sheet zu übertragen. Das würden wir bis Freitag zum Treffen fertig stellen:)

**Comment by Bergmaier** [comment]
Externe Datenbanken sind out of Scope.
