### ISSUE TITLE
Quiz starten

### ISSUE THREAD

**Issue by Ruleya** [sweIhm-ws2018-19/skillproject-fr-33#18]
Als Spieler will ich das Quiz spielen, um etwas interessantes über die Region zu erfahren durch die ich gerade mit dem Auto fahre. 

### Akzeptanzkriterien: 
- Alexa startet das Quiz/den Skill
- Die Skill merkt sich die Spieleranzahl

**Comment by fft5woosh** [comment]
oops

**Comment by fft5woosh** [comment]
![zzzzzz](https://user-images.githubusercontent.com/43741930/48674265-8d910980-eb4a-11e8-8da9-f4dadef5e458.PNG)

Ich habe mal einen Handler eingebaut der die Anzahl der Spieler ermittelt.
Bei korrekter Eingabe, werden diese dann auch als statische Klassenvariablen von ColorPickerStreamHandler (natürrlich heißt die Klasse dann anders, zb ReisequizStreamHandler )
Damit können wir dann die Spielrunden steuern

**Comment by fft5woosh** [comment]
![zzzzzz](https://user-images.githubusercontent.com/43741930/48983681-25b26400-f0f2-11e8-8d98-fc1cd335722d.PNG)
