### ISSUE TITLE
Antwortmöglichkeiten

### ISSUE THREAD

**Issue by Ruleya** [sweIhm-ws2018-19/skillproject-fr-33#20]
Als Spieler will ich vorgefertigte Antowrtmöglichkeiten zu Auswahl haben, um nicht raten zu müssen. 

### Akzeptanzkriterien:
- Alexa gibt zu jeder gestellten Frage drei Antwortmöglichkeiten aus
- Die Antwortmöglichkeiten bestehen aus einer korrekten (festgelegten) und zwei falschen Antworten
- Die zwei falschen Antworten werden zufällig festgelegt (?)

**Comment by Angiabc** [comment]
"_Die zwei falschen Antworten werden zufällig festgelegt (?)_" wir werden in unseren Vorbereitungen für die Datenbank die falschen Antworten vorgeben. Denke das ist am einfachsten oder?

**Comment by Bergmaier** [comment]
Funktioniert!
Es fehlen noch Tests und das Merken des Verwürfelns der Antwortmöglichkeiten.

**Comment by fft5woosh** [comment]
Ich schreibe heute noch Tests für : 
-  QuestionLoader (soll testen ob alle Inhalte der csv richtig eingelesen werden)
-  anderen Klassen aus quiz.model
