### ISSUE TITLE
Mehrspieler-Modus

### ISSUE THREAD

**Issue by Ruleya** [sweIhm-ws2018-19/skillproject-fr-33#27]
Als User möchte ich mit Freunden zusammen das Quiz spielen können. 

### Akteptanzkriterien:
- Das Quiz kann von einem bis zu fünf Spielern gespielt werden

**Comment by Bergmaier** [comment]
Bug:
* Wenn nur ein Spieler spielt muss man „eins“ sagen. Es sollte aber mit „einer, nur ich, ein Spieler“ funktionieren

**Comment by Bergmaier** [comment]
Funktioniert jetzt :-)
