### ISSUE TITLE
Richtige Antwort sagen 

### ISSUE THREAD

**Issue by Angiabc** [sweIhm-ws2018-19/skillproject-fr-33#29]
Hallo :) Uns ist aufgefallen, dass wir noch was entscheidendes vergessen haben:
Und zwar wäre es natürlich wichtig, dass dem Spieler, im Falle, dass er eine falsche Antwort gibt, direkt die richtige Antwort kommuniziert wird. Der Spieler hat also einen Versuch. Die richtige Antwort soll dann ebenfalls zusammen mit der weiterführenden Info (s. Frage-Datenbank Berlin - für die andern beiden bekommt Ihr die weiterführenden Infos noch) gegeben werden.
Danke!

**Comment by Claraabc** [comment]
Als User möchte ich die richtige Antwort auf die Frage wissen.
Akzeptanzkriterium: Alexa sagt nach einer falschen Antwort, was richtig gewesen wäre.

Als User möchte ich mich über die Destination informieren.
Akzeptanzkriterium: Alexa sagt mir die richtige Antwort. Alexa sagt mir eine zusätzliche Information über die Destination.
