### ISSUE TITLE
Implementierung der Fragerunden

### ISSUE THREAD

**Issue by fft5woosh** [sweIhm-ws2018-19/skillproject-fr-33#31]
Die Fragerunden könnten wir folgendermaßen implementieren : 
 Ich habe zum Beispiel den AskQuestionIntentHandler geschrieben. Damit dieser von Alexa
 getriggert wird muss man laut der json fragen : **Stell mir eine Frage**
    
![zzzzzz](https://user-images.githubusercontent.com/43741930/48838524-ecdc5d00-ed88-11e8-9c11-29f5be60eb99.PNG)

Bei samples könnten wir einen Satz hinzufügen, der eine neue Fragerunde startet zb "nächste Runde".
Sagt man zu Alexa "nächste Runde" wird AskQuestionIntentHandler erneut getriggert.
Im ColorPickerStreamHandler können wir eine globale Variable zb **count_questions** definieren die
mit jeder neuen Runde hochzählt und in der handle-Methode von AskQuestionIntentHandler so die
neuen Fragen gestellt werden...

**Comment by Bergmaier** [comment]
> Zum Beispiel ein `AskQuestionIntentHandler`. Damit dieser von Alexa
getriggert wird muss man laut der json fragen: "*Stell mir eine Frage*"

Ich denke das ist genau der falsche Ansatz. Es gibt nicht einen Intent für jede Art von Ausgabe ("Frage stellen"), sondern einen Intent pro Eingabe, welche Art von Äußerung der Benutzer getroffen hat. Da gibt es bei uns im Kern eigentlich nur zwei Stück: Starten und Antworten. Dann muss man im Zustand des Spiels nachsehen welche Folgen das hat, sowohl die Aktion selbst behandeln als auch die nächste Ausgabe finden.
