### ISSUE TITLE
Morgiges Treffen & aktueller Stand

### ISSUE THREAD

**Issue by rena611** [sweIhm-ws2018-19/skillproject-fr-33#33]
Hi zusammen,

ich wollte hier noch einmal schriftlich festhalten, was wir am Freitag besprochen hatten. 

Wir sind dabei bis morgen die Spieler-Level und die User Story für die ,,Zusatzinfo / Insider Tipp" aus zu formulieren. 

Es wäre wichtig, dass bis morgen eine laufende Anwendung steht, mit der man reden kann. Es soll möglich sein eine Runde, also 5 Fragen, die zufällig aus der von uns gelieferten Datenbank ausgewählt werden, durch zu spielen. Bei falscher Antwort soll die richtige Antwort genannt werden und nach der Runde soll der Punktestand genannt werden.

Unser Prof hat uns heute nochmal abgefangen und bisschen Dampf gemacht. Wir haben ihm gesagt, dass wir für morgen ein Treffen mit euch vereinbart haben und dann die ersten Ergebnisse checken möchten. Er möchte dann gerne Feedback von uns haben, wie das Treffen gelaufen ist. 
Den Sprints von Frau Socher zufolge sollte der Prototyp, wie oben genannt, bis morgen eigentlich machbar sein.

Dann bis morgen um 15:30 Uhr bei euch in der FK 07 und viel Erfolg! 

Bei Rückfragen kommt gerne auf uns zu! :)

LG
Verena

**Comment by Bergmaier** [comment]
Hallo,
ich sehe gerade in der FK 07 ist morgen von 15:15-16:45 die studentische Vollversammlung...
Können wir das Treffen vielleicht doch kurzfristig auf 10:00 legen?

**Comment by Claraabc** [comment]
Könntet ihr denn auch am Donnerstag um 15:30 oder 16:00 oder am Vormittag? Da könnten wir dann nämlich alle und morgen um 10 können nur zwei von uns :)

**Comment by Bergmaier** [comment]
Donnerstag haben wir alle 3 bis 16:45 Mathe, danach könnte noch gehen - zumindest bei mir. Lieber wäre mir morgen Vormittag, auch wenn im kleinen Kreis - oder wir gehen halt nicht zur VV, ausgemacht ist ausgemacht.

**Comment by Claraabc** [comment]
Ne passt. Dann morgen um 10 :)

**Comment by fft5woosh** [comment]
Geht doch.
10 Uhr passt

**Comment by Claraabc** [comment]
Wir sind im zweiten Stock im Gang
