### ISSUE TITLE
Erreichtes Level

### ISSUE THREAD

**Issue by Claraabc** [sweIhm-ws2018-19/skillproject-fr-33#34]
Als User möchte ich wissen, wie gut mein Wissen über die Destination schon ist.
Akzeptanzkriterium: Alexa sagt mir nach dem Spiel, welches Level ich erreicht habe.

**Comment by Bergmaier** [comment]
Was ist ein Level? Der Punktestand akkumliert über die verschiedenen Runden?

**Comment by Claraabc** [comment]
Da sind wir noch dran. Wir haben uns schon was überlegt aber würden es dann nochmal bis morgen absprechen...

**Comment by Claraabc** [comment]
Die Level beziehen sich jeweils auf eine Runde mit 5 erreichbaren Punkten:
0 Punkte und 1 Punkt -> Tourist
2&3 Punkte -> Zugezogener
4 Punkte -> Stadtführer
5 Punkte -> Einheimischer

Und hier noch die Dialoge dafür:
0: Schade, du hast leider keine Frage richtig beantwortet. Versuch es doch gleich noch einmal. Beim nächsten mal klappt's bestimmt besser. Hier dein Level: du bist ein Tourist.
1: Schade, du hast leider nur einen Punkt erreicht. Versuch es doch gleich noch einmal. Beim nächsten mal klappt's bestimmt besser. Hier dein Level: du bist ein Tourist.
2&3: Du hast [2;3] Punkte erreicht und musst noch ein bisschen üben. Hier dein Level: du bist ein Zugezogener.
4: Super, du hast 4 Punkte erreicht. Das ist schon richtig gut. Hier dein Level: du bist ein Stadtführer.
5: Sehr gut, du hast alle Fragen richtig beantwortet! Du weißt ja wirklich alles. Hier dein Level: du bist ein Einheimischer.

**Comment by Bergmaier** [comment]
Soll das nach jeder Runde ausgegeben werden oder erst am Schluss, wenn das Spiel beendet wird? Wir waren uns jetzt nicht mehr sicher.

**Comment by Claraabc** [comment]
Hey :) Das Level bitte erst, wenn das Spiel beendet ist. Aber trotzdem nach jeder Runde der Punktestand.

**Comment by Bergmaier** [comment]
Ok, wir müssen also die Punktestände über mehrere Runden hinweg merken. Wie kommt dann das Level zustande, wenn ich nach 3 Runden mit unterschiedlichen Punkten pro Runde das Spiel beende (#38)? Oben steht noch "*Die Level beziehen sich jeweils auf eine Runde*". Soll am Schluss dann das durchschnittliche Level ausgegeben werden? Oder das der besten Runde? Oder etwas anderes?

**Comment by Claraabc** [comment]
Sorry, das war von uns unverständlich formuliert. Ein durschnitt der Punkte für das Level am Ende wäre gut. Wir haben uns überlegt, ob man das evtl. so berechnen kann, dass wenn als Punkteschnitt am Ende 3,3 rauskommt, auf drei abgerundet wird und ab 0,5 jeweils aufgerundet...

**Comment by fft5woosh** [comment]
Ich habe mal einen **QuizEndHandler** erstellt.
Dieser soll, laut Auftrag, die Level der Spieler ausgeben.
Er ist noch unvollständig ( wenn man mit ^weiter^ weiterspielen möchte dann... naja noch nichts.. **lol**) Leider hakt es noch, da die Spieler und deren
Scores noch nicht in den SessionAttributes gespeichert werden.
Falls der Name schon mit einem anderen Handler (zb. soll wenn man "Mir reicht´s" sagt, soll ja ein Quit Handler igwie getriggert werden) kann dieser natürlich umgeschrieben werden.
