### ISSUE TITLE
Weiterführende Infos

### ISSUE THREAD

**Issue by Angiabc** [sweIhm-ws2018-19/skillproject-fr-33#35]
Hey :)
Von mir gibt´s hier noch mal die Quizfragen für die Ostsee, allerdings mit den zusätzlichen Infos/Tipps, die haben bis jetzt noch gefehlt.
Lg Angi

[Quizfragen Ostsee mit Info.xlsx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2621520/Quizfragen.Ostsee.mit.Info.xlsx)

**Comment by Bergmaier** [comment]
Hallo, könnt ihr noch eine Userstory für die weiterführendes Infos anlegen? (So wie bei #29, das war gut)

**Comment by Claraabc** [comment]
Als User möchte ich etwas neues über die Destination lernen.

Akzeptanzkriterium: 
Alexa nennt mir nach der richtigen Antwort noch eine weiterführende Information, die in Zusammenhang mit der gestellten Frage steht.

**Comment by fft5woosh** [comment]
> Hey :)
> Von mir gibt´s hier noch mal die Quizfragen für die Ostsee, allerdings mit den zusätzlichen Infos/Tipps, die haben bis jetzt noch gefehlt.
> Lg Angi
> 
> [Quizfragen Ostsee mit Info.xlsx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2621520/Quizfragen.Ostsee.mit.Info.xlsx)

Ist gut ^^
Nur eine kleine Sache :-) Die Spaltennamen müssen die Selben sein, wie in der Berlin Excel
