### ISSUE TITLE
Intonation Sprachausgabe

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#39]
Bei vielen Äußerungen von Alexa fehlen noch realistische Pausen, Höhen und Tiefen.

**Comment by Bergmaier** [comment]
Aussprache nicht richtig:
-	 „Du hast eins Punkte erreicht“
-	Wer sagte: Berlin, die größte kulturelle Extravaganz, die man sich vorstellen kann. -> „minus“
-	Kilometerangaben und Autobahnen werden nicht richtig ausgesprochen
-	Die Spielernamen Mickey und Minney werden nicht richtig ausgesprochen
-	Bei Höhenangaben oder Entfernungen sagt Alexa immer „minus“ vor der Zahl. Z.B: „Wie hoch ist der Dresdner Fernsehturm ? a) minus…

**Comment by Bergmaier** [comment]
Hallo, wir haben heute herausgefunden dass man sich in der [Alexa Skills Console](https://developer.amazon.com/alexa/console/ask) auch beliebigen Text (mit Speech-Markup) vorlesen lassen kann. Dazu den Skill auswählen, auf "Test" gehen, und dann auf "Voice & Tone" umstellen. So könnt ihr euch schon mal ausgewählte Fragen anhören.

**Comment by Claraabc** [comment]
Hey hier nochmal für Dresden die überarbeitete Datei. Wenn man die Antwortmöglichkeiten in dieser Form eingibt, hat Alexa sie immer mit richtigen Pausen vorgelesen: a) Haus. b) Baum. c) Maus.
Ich hab jetzt also nach jede Antwort einen Punkt gemacht bzw. nach Zahlen eine Pause. Woher das mit dem Minus kam bei Längen und Höhenangaben weiß ich nicht - jedenfalls kam es beim testen jetzt nicht...
[Dresden Quizfragen.xlsx1.xlsx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2713278/Dresden.Quizfragen.xlsx1.xlsx)

Könntet Ihr bitte für die Spielernamen Mickey und Minney jeweils als Sprache Englisch einsetzen, damit sie es richtig ausspricht? ( < lang xml:lang="en-US">Mickey< /lang > und < lang xml:lang="en-US">Minney< /lang > )

**Comment by Angiabc** [comment]
Hey :) Hier auch von mir die gecheckte Version von der Ostsee.
[Quizfragen Ostsee mit Info.xlsx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2720583/Quizfragen.Ostsee.mit.Info.xlsx)

**Comment by Ruleya** [comment]
Gibt es das für Berlin auch noch? Falls nicht, macht euch keinen Aufwand, wir können die Endungen auch automatisch anfügen.

**Comment by Bergmaier** [comment]
TODO: "Du hast eins Punkte erreicht“

**Comment by Angiabc** [comment]
Hey :)
Anbei unsere Präsentation. Wenn ihr wollt, könnt Ihr Euren Slide da einfügen, dann haben wir alles zusammen. Falls ja, dann bräuchten wir die fertige Präsi heute noch, weil wir sie für unseren Prof auf die Dropbox hochladen müssen.
[OnTouri.pptx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2745879/OnTouri.pptx)

Eine Sache noch: Wäre es möglich, dass Alexa nach der Ausgabe des Levels in Demo & normaler Version noch sagt "Tschüss, bis zum nächsten Mal"?
Und habt Ihr an den Auto-Sound beim Start noch gedacht? <audio src='soundbank://soundlibrary/transportation/amzn_sfx_car_honk_3x_02'/>

Danke!!

**Comment by Bergmaier** [comment]
Die Präsentation für euren Prof muss bestimmt unseren Slide nicht enthalten, ich denke ihr könnt das schonmal hochladen.

"Tschüss" können wir noch einfügen. Welchen Autosound wollt ihr haben? (URL der Audiodatei)

**Comment by Angiabc** [comment]
<audio src='soundbank://soundlibrary/transportation/amzn_sfx_car_honk_3x_02'/>

**Comment by Angiabc** [comment]
audio src='soundbank://soundlibrary/transportation/amzn_sfx_car_honk_3x_02'/

**Comment by rena611** [comment]
Wäre es möglich bis zur präsi noch zu ändern, dass Alexa sagt ,,du hast einEN Punkt“? Leider sagt sie immer noch, ,,du hast einS Punkte“. 
Das wäre zumindestens für die demo ziemlich wichtig.

**Comment by Bergmaier** [comment]
Haben wir schon, ist leider noch nicht online. Kommt gleich.
