### ISSUE TITLE
Bessere Unterscheidung der Intents

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#41]
Alexa hat Probleme, den richtigen Intent zu erkennen, gerade bei unvernünftigen Äußerungen oder solchen die nicht in unserem Modell hartkodiert sind. "München" wird beispielsweise nicht als Region erkannt (nur "Berlin", "Dresden" und "Ostsee" sind erlaubt) also wird als "StartQuiz"-Äußerung wahrgenommen.

Bei dem Matching kann leider der Zustand unseres Skill nicht berücksichtigt werden - Alexa weiß nicht, dass wir gerade eine Quizfrage gestellt haben oder eine Frage nach der Spielregion oder der Spieleranzahl. Hier müssen wir uns noch etwas einfallen lassen. Gerade die sehr generisch gehaltenen Äußerungen für den "StartQuizIntent" werden oft an der falschen Stelle erkannt. Hier brauchen wir noch einen allgemeinen Handler, der die Äußerungen anhand des Spielzustands beurteilt und dann die richtige Aktion aufruft.

Bug:
* Wenn man die Antwort (also nicht abc) als Antwort gibt, kommt es zu Fehlern: entweder wird nicht richtig/falsch gesagt und keine Zusatzinfo oder es kommt eine Fehlermeldung und das Spiel bricht ab

**Comment by Ruleya** [comment]
Alexa hat ein weiteres Problem mit den Antwortmöglichkeiten A, B und C. Wenn man nicht "Antwort" oder ähnliches vorne anstellt, wird die Antwort gar nicht erkannt und eine neue Runde gestartet, da einzelne Buchstaben wohl nicht erkannt werden

**Comment by Bergmaier** [comment]
Solved with https://forums.developer.amazon.com/questions/9331/letter-of-the-alphabet-slot-type.html

**Comment by Bergmaier** [comment]
Proposed solution:
- Dialogzustand speichern ("letzte Frage"): Zustandsautomat in Spiel-Fachklasse

**Comment by Bergmaier** [comment]
Also: Use [Dialog States](https://developer.amazon.com/docs/custom-skills/define-the-dialog-to-collect-and-confirm-required-information.html)!

Insbesondere die [Elicit Slot Directive](https://developer.amazon.com/docs/custom-skills/dialog-interface-reference.html#elicitslot):

> `Dialog.ElicitSlot` does use the utterances you provide for the slot. Alexa **biases the interaction model to listen for the utterances defined for the slot**, so it is important to provide good utterances when you define the dialog model.

**Comment by Bergmaier** [comment]
Not as useful as I hoped, though: https://forums.developer.amazon.com/questions/67926/dialog-modelinterface-dialogstate-on-launch-reques-1.html

**Comment by Bergmaier** [comment]
Bugs:
* Wenn mitten im Spiel eine neue Runde gestartet wird (per `StartRoundIntent`), wird der aktuelle Spielstand (bisherige Punktzahlen, bereits gefragte Fragen) nicht berücksichtigt
* Auch wenn `toNextQuestion` keine weiteren Fragen hat, wird in den Zustand `QUIZ_QUESTION` gewechselt und die letzte nochmal gestellt

**Comment by Bergmaier** [comment]
Not as useful as I hoped, though: https://forums.developer.amazon.com/questions/67926/dialog-modelinterface-dialogstate-on-launch-reques-1.html

**Comment by Bergmaier** [comment]
WTF:
![grafik](https://user-images.githubusercontent.com/44295860/50923200-b0ee7b80-144c-11e9-9399-24b34b37692c.png)
Ich hoffe sehr das war nur ein Glitch.
