### ISSUE TITLE
Kommunikation

### ISSUE THREAD

**Issue by Angiabc** [sweIhm-ws2018-19/skillproject-fr-33#43]
Hallo :) Wir haben euch die Kommunikation aus Github jetzt extra nochmal in ein Word Dokument übertragen. Wir hoffen, dass es so jetzt leichter verständlich für euch ist. Fragt gerne jederzeit nach, falls noch was unklar ist.
[Alexa Kommunikation.docx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2657289/Alexa.Kommunikation.docx)

**Comment by Bergmaier** [comment]
Ehrlich gesagt, leichter verständlich wäre es gewesen wenn ihr das im Wiki upgedated hättet (das hat auch eine Versionshistorie und Änderungsverfolgung) :-)
Aber ja, das Dokument ist gut verständlich, damit können wir arbeiten. Danke!
