### ISSUE TITLE
Unit-Tests

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#46]
Write useful unit tests, using the questions from the "Test" region.

* [ ] Get familiar with Mockito
* [ ] Rip off tests from [skillproject-fr-15](https://github.com/sweIhm-ws2018-19/skillproject-fr-15/tree/master/src/test/java/alexasescape)
* [x] Get good coverage

**Comment by fft5woosh** [comment]
Ist das auch für mich ? :-O

**Comment by Bergmaier** [comment]
Fang gern damit an :-) Ich wollte jetzt niemand assignen. Gehört auch eigentlich nicht mehr zum Sprint2-Backlog...

**Comment by fft5woosh** [comment]
Ich würde den Skill Tester von Kay lerch https://github.com/KayLerch/alexa-skills-kit-tester-java
probieren.
Hab mal die pom dependency in den fft5woosh branch gepusht

**Comment by Bergmaier** [comment]
Für die Unit-Tests brauchen wir eigentlich kein Framework - das soll wirklich nur unsere `model`-Klassen testen (und alles mocken, was nötig ist). Der Code in den Handlern ist trivial (wenn nicht, gehört er in das Model refactored) und wird von den End-to-End-Tests #47 abgedeckt (das läuft übrigens schon! wenn auch ohne check der ergebnisse).

**Comment by Ruleya** [comment]
Über 50% Coverage erreicht
