### ISSUE TITLE
End-to-End tests

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#47]
Write an end-to-end test suite that reads in complete JSON requests from a directory of examples and compares the output against the expected result.

* [x] Directly call [`Skill:handleRequest`](http://ask-sdk-java-javadocs.s3-website-us-west-2.amazonaws.com/com/amazon/ask/SkillStreamHandler.html#handleRequest-java.io.InputStream-java.io.OutputStream-com.amazonaws.services.lambda.runtime.Context-) (probably with a mocked Context)
* [ ] Get 100% coverage!

**Comment by fft5woosh** [comment]
Ist das für mich ?
 :-)

**Comment by Bergmaier** [comment]
`QuizStreamHandler` got 100% coverage :fireworks:

**Comment by Bergmaier** [comment]
Note to self: the `session.user`, `context.System` and `context.device` in the input JSON are optional and can be omitted to anonymize the tests.

**Comment by Bergmaier** [comment]
Die [alexa-skills-kit-tester-java](https://github.com/KayLerch/alexa-skills-kit-tester-java)-Library sieht wirklich interessant aus, danke @fft5woosh! Sie scheint eher auf Überwachung von laufenden Endpoints ausgelegt zu sein, die [YAML-Skripts](https://github.com/KayLerch/alexa-skills-kit-tester-java#yaml-scripts) sind aber genau was ich mir vorgestellt hatte. Und

> **AlexaRequestStreamHandlerEndpoint**: Fires a sequence of requests payloads at your speechlet handler implementation in Java. This only works for skills written in Java and could be used for unit testing.
> ```java
> final AlexaEndpoint endpoint = AlexaRequestStreamHandlerEndpoint.create(MySpeechlet.class).build();
> ```
> You directly point to the entry class of your skill written in Java that implements the SpeechletRequestStreamHandler. You could also give it an instance in case you'd like to mock you test object.

scheint genau das zu sein was wir brauchen - nur das es leider noch auf Speechlets (ASK 1.0) setzt. Mal sehen wie viel wir davon verwenden könne.
