### ISSUE TITLE
Testing Projektteam

### ISSUE THREAD

**Issue by Claraabc** [sweIhm-ws2018-19/skillproject-fr-33#49]
Hallo :) Wir haben den Skill jetzt auf dem Echo getestet und für einen bis fünft Spieler mal alles durchgespielt. Leider habt ihr einige Sachen noch gar nicht umgesetzt und außerdem ein paar Sachen falsch umgesetzt. Zum Beispiel habt ihr schon wieder unsere Dialoge gekürzt. Wir haben euch eine Übersicht erstellt, was wir beim Testing alles gefunden haben. Die ersten beiden Punkte "Noch nicht umgesetzt" und "Nicht so umgesetzt, wie es vereinbart war" sollten bitte bis morgen auf jeden Fall ausgebessert werden. Darin kommt nichts neues vor, sondern nur Dinge, die wir bereits bei unseren Treffen abgesprochen und in Github festgehalten haben und sollten daher machbar sein. Die Bugs, weitere Optimierungspunkte und Aussprachefehler können wir dann nach unserer Präsentation morgen angehen. 
Wir hoffen ihr könnt nachvollziehen, dass dieses Fach für uns wirklich wichtig ist und dreimal so viel in unsere Bachelor-Note zählt, als einfache Klausuren. Außerdem soll laut unserem Prof morgen der "Finale Schulterblick" sein und bis auf Kleinigkeiten, wie die Aussprache, alles laufen. Das komplette Issues einfach noch nicht umgesetzt wurden können wir vor unserem Prof einfach nicht bringen, wenn wir überhaupt bestehen wollen.

Hier das Dokument: [Testing.docx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2675638/Testing.docx)
@Ruleya @fft5woosh @Bergmaier

**Comment by Bergmaier** [comment]
Hallo,
alles werden wir bis morgen nicht schaffen. Die Dialoge am Anfang haben wir mit Absicht gekürzt, da die Ortung (#16 - geplant für den nächsten Sprint) noch nicht funktioniert. Auch dass man den Antworttext selbst sagen kann war für morgen noch nicht geplant.
Dass die Spielregeln (zurzeit in der Hilfefunktion) am Anfang vorgestellt werden, können wir vermutlich noch einbauen. Sound und "mir reichts" geht schnell. Auch die Umstellung auf 5 Fragen, und die richtige Äußerung bei "nicht verstanden" werden wir noch einbauen.
Der letzte Satz bei der Spielerzahlauswahl wurde mit Absicht weggelassen, da er unpassend wäre wenn danach noch die Region ausgewählt werden muss. Wir können das denke ich noch so umbauen dass zuerst nach der Region gefragt wird, erst danach nach der Spieleranzahl.
Den Dialog "deine erste/zweite/... Frage" haben wir übersehen, danke für die Erinnerung.

Der Bug mit den teils total unpassenden Antworten (einfach weitermachen), wenn eine Äußerung falsch interpretiert wurde, ist bekannt (#41). Das kriegen wir erst im nächsten Sprint hin, da wir unsere Architektur dazu neu aufbauen müssen.
Die andere Bugs kann ich nicht nachvollziehen. Bei mir werden die Level beim Beenden des Spiels korrekt ausgegeben. Und dass ich nach dem Beenden des Spiels nicht weiterspielen kann ist so vorhergesehen - der Skill wird geschlossen. Was soll stattdessen passieren?
Eine Fehlermeldung ("es ist ein Problem aufgetreten" oder so) sollte eigentlich nicht mehr auftreten. Wie genau ist das passiert, was habt ihr gesagt? Wir werden dan versuchen das nachzustellen und zu beheben.

**Comment by Bergmaier** [comment]
Hallo,
wir hoffen die im Dokument angesprochenen Probleme im dritten und letzten Sprint alle zu lösen. Ich habe für die noch offenen Punkte einzelne Issues erstellt, bitte schaut mal drüber [was wir alles vorhaben](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues?q=is%3Aissue+milestone%3A%22Sprint+3%22) ("Milestone Sprint 3"). Fehlt noch etwas? Falls nicht, dann würde ich dieses Issue hier gerne schließen.

**Comment by Claraabc** [comment]
Hey :) gut danke. Ja dann kannst du das hier schließen.
