### ISSUE TITLE
Name updaten

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#53]
An allen Stellen wo es vorkommt: Reisequiz -> onToury

* Skill name
* Invocation name
* Readme
* Webseite
* ...?

**Comment by Ruleya** [comment]
Invocation name wurde geändert - wenn ihr den Skill testen woll -> starte OnToury

**Comment by Ruleya** [comment]
In eurer Präsi steht OnToury jetzt mit i. Hat sich die Schreibweise geändert oder war das ein Fehler?

**Comment by rena611** [comment]
Danke für den Hinweis, es bleibt bei onToury.
