### ISSUE TITLE
Blatt 2 Aufgabe 7

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#9]
Ist vergessen worden?

**Comment by fft5woosh** [comment]
2 und 5 sind optional... und 7 gehört dazu.
Genau, danke

**Comment by Bergmaier** [comment]
5c1c5f9c63 LGTM. Evtl. noch Verknüpfungen zwischen den Klassen hinzufügen, entsprechend ihrer Attribute?

**Comment by fft5woosh** [comment]
Doch die müssten passen.
Im Klassendiagramm entsprechen die Verküpfungen (oder Assoziationen zwischen den Klassen) den Klassenattributen.

**Comment by Bergmaier** [comment]
Ja, kann man beides machen. Vorteil der Assoziation: man könnte den Namen des Attributs weglassen, weil den kennen wir nicht wirklich :-)
